### ISSUE TITLE
Gemma model quantization or implementation seems botched

### ISSUE THREAD

**Issue by horiacristescu** [ollama/ollama#2689]
I tried the gemma model today and it responds with
- inconsistent formatting, such as using two commas instead of one
- inconsistent phrasing, such as a noun not being at plural when it should, or absurd phrases like "copyright infringement is being violated"

I tried the same model on labs.perplexity.ai and their version seems to be coherent.

I used `Gemma:7b-Instruct-Q5_K_M`

**Comment by penguinpatroller** [comment]
This is probably the same issue as #2650. Still unresolved.

**Comment by jmorganca** [comment]
Hi there, sorry about this. This should be fixed now. You can de-download the latest models by running:

```
ollama pull gemma
ollama pull gemma:7b # same as above
ollama pull gemma:2b
```

**Comment by mathiscode** [comment]
I was still experiencing this with the latest model of gemma:7b-instruct and completely killing ollama and restarting seems to have fixed the issue for me.

**Comment by Gautamshahi** [comment]
How did you check the quantization? I couldn't find in model description https://ollama.com/library/gemma:7b-instruct-q3_K_M/blobs/bc1362d999cf
