### ISSUE TITLE
ollama.ai certificate has expired, not possible to download models

### ISSUE THREAD

**Issue by psy-q** [ollama/ollama#3336]
### What is the issue?

The ollama.ai certificate has expired today, ollama now can't download models:

```
ollama run mistral
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/mistral/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-03-25T08:28:33+01:00 is after 2024-03-25T07:17:47Z
```

### What did you expect to see?

You should be able to pull models using the `ollama` command.

### Steps to reproduce

Try to pull a model.

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.29

### GPU

Nvidia

**Comment by mteletin** [comment]
Could it be a validation bug? One time is UTC, the other one is not and the error says that the time is in the future basically.
It's clear that one has Z (UTC) the other one does not.

**Comment by ssams** [comment]
> Could it be a validation bug? One time is UTC, the other one is not and the error says that the time is in the future basically. It's clear that one has Z (UTC) the other one does not.
> 
> This "current time 2024-03-25T08:28:33+01:00 is after 2024-03-25T07:17:47Z" is obviously not true. (I'm having the exact same issue now and it will probably go away in a couple of hours once the time zone difference does not produce this effect any more).

2024-03-25T08:28:33+01:00 is equal to 2024-03-25T07:28:33Z ... 07:28 > 07:17. this is not about timezones, the certificate really has expired just a few minutes ago. we'll need to wait until an admin of the service can update the certificate.

**Comment by mteletin** [comment]
> > Could it be a validation bug? One time is UTC, the other one is not and the error says that the time is in the future basically. It's clear that one has Z (UTC) the other one does not.
> > This "current time 2024-03-25T08:28:33+01:00 is after 2024-03-25T07:17:47Z" is obviously not true. (I'm having the exact same issue now and it will probably go away in a couple of hours once the time zone difference does not produce this effect any more).
> 
> 2024-03-25T08:28:33+01:00 is equal to 2024-03-25T07:28:33Z ... 07:28 > 07:17. this is not about timezones, the certificate really has expired just a few minutes ago. we'll need to wait until an admin of the service can update the certificate.

you are right, was thinking about beginning dates not end dates... my bad

**Comment by agentgill** [comment]
I downloaded only this morning, was able to successfully download mistral, then went to download gemma and hit this error

**Comment by memamun** [comment]
I am also facing this error:
ollama run llama2
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-03-25T13:43:33+06:00 is after 2024-03-25T07:17:47Z

**Comment by spagliarini** [comment]
I am also facing the same error when pulling models.

**Comment by BothSavage** [comment]
i hit this error too,waiting.....

**Comment by gqf2008** [comment]
me too

**Comment by gavink97** [comment]
+1

**Comment by Henmanolc** [comment]
Not really helpful, I guess, but I am facing the issue as well.

**Comment by MMHHRR** [comment]
waiting...

**Comment by eramax** [comment]
same here.

**Comment by Officialstrike** [comment]
Please refrain from commenting "+1", "waiting," "me too," "same here," or any derivative thereof; instead, please like the original post! The comments should be used to add useful contributions.

**Comment by renhiyama** [comment]
@Officialstrike is it possible to bypass this warning/error by some `--force` command or changing timezone temporarily?

**Comment by Officialstrike** [comment]
Current temporary workaround: set your clock a couple of hours before `Mon, 25 Mar 2024 07:17:47 GMT`.

**Comment by kaetemi** [comment]
sudo systemctl stop systemd-timesyncd
sudo date -s '-2 hours'

To turn your clock back on Ubuntu

**Comment by Officialstrike** [comment]
> @Officialstrike is it possible to bypass this warning/error by some `--force` command or changing timezone temporarily?

Yes, see my earlier comment about setting your clock backwards

**Comment by renhiyama** [comment]
Thanks it worked for me!

**Comment by SuperSonnix71** [comment]
I figured that  workaround would be to change the date to before 2024-02-09T20:53:22Z
but still i cannot pull any models.....
pulling manifest 
Error: pull model manifest: 401

**Comment by hhyqhh** [comment]
> sudo systemctl stop systemd-timesyncd sudo date -s '-2 hours'
> 
> To turn your clock back on Ubuntu

The method was incredible but it did solve the problem!! 😀

**Comment by soone** [comment]
I am waiting

**Comment by raazuregai** [comment]
same here.
Waiting.

**Comment by Officialstrike** [comment]
> Please refrain from commenting "+1", "waiting," "me too," "same here," or any derivative thereof; instead, please like the original post! The comments should be used to add valuable contributions, and liking the original post makes it clear that you are also affected.

repost (so please are setting it)

**Comment by bamous12** [comment]
same:
ollama run gemma
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/gemma/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

**Comment by dafei1288** [comment]
same too:

ollama run starcoder
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/starcoder/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

**Comment by SlumberDemon** [comment]
> same too:
> 
> ollama run starcoder pulling manifest Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/starcoder/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

Stop commenting that, it won't fix the issue

**Comment by MoonRide303** [comment]
Guys, seriously - you need to either manage and renew your certificates on time, or configure some automation for that (certbot / whatever).

**Comment by alperhankendi** [comment]
> **Please refrain from commenting "+1", "waiting," "me too," "same here," or any derivative thereof**; instead, **please like the original post!** The comments should be used to add valuable contributions, and liking the original post makes it clear that you are also affected.
> 
> _repost (so please are seeing it)_

same here

**Comment by Lase9** [comment]
same

**Comment by awillSoftwares** [comment]
sudo systemctl stop systemd-timesyncd
sudo date -s '-2 hours'
solves this

**Comment by dafei1288** [comment]
> sudo systemctl stop systemd-timesyncd sudo date -s '-2 hours' solves this

itworks !!

**Comment by BothSavage** [comment]
<img width="689" alt="image" src="https://github.com/ollama/ollama/assets/38107458/f27f36fc-0683-40a2-a9e4-2f4d1d2d4b8c">


macos -2 hours really works ,thanks

**Comment by Henmanolc** [comment]
Also works on Windows 11 when manually changing the time through system settings. Thanks, downloading right now :)

**Comment by MMHHRR** [comment]
wind 10 work, -2 hours really works ,thanks

**Comment by WShawnMing** [comment]
root@DESKTOP-ShawnMing:/home/shawn# timedatectl
               Local time: Mon 2024-03-25 16:51:35 CST
           Universal time: Mon 2024-03-25 08:51:35 UTC
                 RTC time: Mon 2024-03-25 08:51:35
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no                   i used the commands above ,System clock synchronized status is still yes,why?

**Comment by WShawnMing** [comment]
> root@DESKTOP-ShawnMing:/home/shawn# timedatectl Local time: Mon 2024-03-25 16:51:35 CST Universal time: Mon 2024-03-25 08:51:35 UTC RTC time: Mon 2024-03-25 08:51:35 Time zone: Asia/Shanghai (CST, +0800) System clock synchronized: yes NTP service: inactive RTC in local TZ: no i used the commands above ,System clock synchronized status is still yes,why?

ok ,my fool,i have finished it

**Comment by ShamithaReddy** [comment]
> Current temporary workaround: set your clock a couple of hours before `Mon, 25 Mar 2024 07:17:47 GMT`.

Setting it around 25th March 7: 20 AM IST is only working, and when i tried any other time, its giving the below error

`Error: pull model manifest: 401`

**Comment by erictroebs** [comment]
> > Current temporary workaround: set your clock a couple of hours before `Mon, 25 Mar 2024 07:17:47 GMT`.
> 
> Setting it around 25th March 7: 20 AM IST is only working, and when i tried any other time, its giving the below error
> 
> `Error: pull model manifest: 401`
Do not increase the offset to more than a few hours. I tried two days first and it did not work.

**Comment by Officialstrike** [comment]
> > Current temporary workaround: set your clock a couple of hours before `Mon, 25 Mar 2024 07:17:47 GMT`.
> 
> Setting it around 25th March 7: 20 AM IST is only working, and when i tried any other time, its giving the below error
> 
> `Error: pull model manifest: 401`

It is important you change your system clock, not your visual clock!

**Comment by dongwang22** [comment]
Come on. Somebody fix it! This is the first time I have tried LLama. I even thought it was my fault to cause the error.

**Comment by fjibj** [comment]
oh, my god, it's terrible.

**Comment by vcredit-azure** [comment]
the same problem

**Comment by AryaFeng** [comment]
> > > sudo date -s '-2 hours'
> > 
> > 
> > At first, it had an effect. However, about halfway through the download, the error was reported again. And then re-execute, still error
> 
> Just remove some more hours, the certificate expired at 7:19 (UTC) this morning. It will work till you are earlier on your system.

thanks! it is work

**Comment by gillbates** [comment]
same issue here ...

**Comment by MaxTheTurtle0** [comment]
same issue here

**Comment by DevRaeph** [comment]
no fix yet

**Comment by XiandanErizo** [comment]
> > > > sudo date -s '-2 hours'
> > > 
> > > 
> > > At first, it had an effect. However, about halfway through the download, the error was reported again. And then re-execute, still error
> > 
> > 
> > Just remove some more hours, the certificate expired at 7:19 (UTC) this morning. It will work till you are earlier on your system.
> 
> thanks! it is work

no it doesn't work

**Comment by SangeloDev** [comment]
@DevRaeph 
@XiandanErizo

you can set back your system clock to trick your system into thinking that the certificate is still valid. the certificate expired at 7:19 (UTC).
this is a workaround until the system administrators renew the certificate.

**Comment by MaxTheTurtle0** [comment]
> @DevRaeph @XiandanErizo
> 
> you can set back your system clock to trick your system into thinking that the certificate is still valid. the certificate expired at 7:19 (UTC). this is a workaround until the system administrators renew the certificate.

I tried that on wsl 2 but it didnt fix it

**Comment by Lase9** [comment]
it works on 1:43 am 03/25/2024

**Comment by SangeloDev** [comment]
> > @DevRaeph @XiandanErizo
> > you can set back your system clock to trick your system into thinking that the certificate is still valid. the certificate expired at 7:19 (UTC). this is a workaround until the system administrators renew the certificate.
> 
> I tried that on wsl 2 but it didnt fix it

have you tried setting the windows system clock? in your settings.

**Comment by AryaFeng** [comment]
> > > > > sudo date -s '-2 hours'
> > > > 
> > > > 
> > > > At first, it had an effect. However, about halfway through the download, the error was reported again. And then re-execute, still error
> > > 
> > > 
> > > Just remove some more hours, the certificate expired at 7:19 (UTC) this morning. It will work till you are earlier on your system.
> > 
> > 
> > thanks! it is work
> 
> no it doesn't work

i dont know why you not work, it does work, i  change -2 to -10  make sure time early the 7:19 (UTC)  。"sudo date -s '-10 hours'"。 hope for help you

**Comment by ghzgod** [comment]
I think the issue is that the registry pulls from ollama.ai and not ollama.com and that is with the latest docker container image

**Comment by MaxTheTurtle0** [comment]
> > > @DevRaeph @XiandanErizo
> > > you can set back your system clock to trick your system into thinking that the certificate is still valid. the certificate expired at 7:19 (UTC). this is a workaround until the system administrators renew the certificate.
> > 
> > 
> > I tried that on wsl 2 but it didnt fix it
> 
> have you tried setting the windows system clock? in your settings.

was trying that rn and now it works

**Comment by tevino** [comment]
Also `--insecure` is not working:

```shell
> ollama pull mistral --insecure
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai:443/v2/library/mistral/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “ollama.ai” certificate is expired
```

According to the help, it should be able to ignore the expired certificate:
```shell
> ollama pull --help
Pull a model from a registry

Usage:
  ollama pull MODEL [flags]

Flags:
  -h, --help       help for pull
      --insecure   Use an insecure registry

Environment Variables:
      OLLAMA_HOST        The host:port or base URL of the Ollama server (e.g. http://localhost:11434)
```

**Comment by Ust-Waylon** [comment]
Is there a solution other than changing the system time? :-)

**Comment by tushgaurav** [comment]
I don't want to change my system time, is there any other workaround?

**Comment by Jericho1060** [comment]
The problem seems solved for me

**Comment by dadidelux** [comment]
how to solve it?

**Comment by viniciusfont** [comment]
I fixed by setting the system clock to 6:36 UTC 25 March 2024

**Comment by yuancjun** [comment]
New problems have arisen.
···
ollama run qwen:14b
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai:443/v2/library/qwen/manifests/14b": stopped after 10 redirects
···

**Comment by Nathanule** [comment]
same problem here
ollama pull llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai:443/v2/library/llama2/manifests/latest": stopped after 10 redirects

**Comment by Kapuzinaa** [comment]
Certificate seems updated, now i get 
pull model manifest: unauthorized

**Comment by meet447** [comment]
> Certificate seems updated, now i get pull model manifest: unauthorized

facing the same issue

**Comment by Kapuzinaa** [comment]
updated: now is the following error displayed.
pull model manifest: 500

**Comment by latenssi** [comment]
Had this issue but it is working for me now,

**Comment by cr2007** [comment]
**Update:** I am able to pull the models successfully now

![image](https://github.com/ollama/ollama/assets/73425927/f15b5f76-725b-46e4-aa98-ddfceac36ae4)

**Comment by mustafa-198** [comment]
guys after i changed the time new error apears "pull model manifest: unauthorized" and i solve it simply by restart my computer now it's downloading

**Comment by m4r1k** [comment]
I'm still getting `unauthorized`

```bash
$ ollama pull llava:7b
pulling manifest
Error: pull model manifest: unauthorized
```

**Comment by dylan2019** [comment]
pulling manifest
Error: pull model manifest: file does not exist

**Comment by mteletin** [comment]
Guys, it's working. Certificate issue was fixed. Whatever other issues you have must be something specific to your ISP or caches or other things. I'm just pulling some models for test right now just fine (see previous morning and now).
![image](https://github.com/ollama/ollama/assets/10918175/216b8dbd-9544-44d9-b33c-193f2dd0338e)

**Comment by jmorganca** [comment]
Hi everyone, this should be fixed now. I'll leave this issue open for a bit longer and provide a longer explanation on what happened here soon (we don't take availability issues like this lightly). Please let me know if you're seeing any more issues!

**Comment by taozhiyuai** [comment]
> sudo systemctl stop systemd-timesyncd sudo date -s '-2 hours'
> 
> To turn your clock back on Ubuntu

but how to fix this issue? :(

**Comment by ipty** [comment]
Hi there,
is there anything i need to do - i still get the mentioned ssl error.
This it what it looks like if i put the download link in a browser:
![ssl](https://github.com/ollama/ollama/assets/9331981/d3b5846a-8cae-4815-9fc6-94bde5a1d365)

Kind regards 
Erik

**Comment by MoonRide303** [comment]
It works fine for me, now (ollama run correctly pulls models). Maybe you guys need to clear some caches / restart the machine.

**Comment by Jagrmi-C** [comment]
Fixed, I'm waiting 8 hours without efforts and ran again pull

**Comment by eatcosmos** [comment]
kill ollama serve and restart serve multi times, then run again

**Comment by Symbolk** [comment]
> sudo systemctl stop systemd-timesyncd sudo date -s '-2 hours'
> 
> To turn your clock back on Ubuntu

Tried but with no luck, I am changing inside a Docker, not the ollama one, the Ubuntu 22.04

**Comment by VeluAtHPE** [comment]
how to resolve this issue: 

(base) root@toolsvm:/var/www/html/playground/ollama# ollama pull dolphin-llama3 --insecure
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/ea/ea025c107c1c3e5a87380b25e205db3b19a4d2ed56f1954f531573a963621580/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240615%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240615T114017Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=66ecd8cd6dfd1c992ba8f5e6bbd27e51f56663bcd8c7ffdf7ecb9f1ed7387b3b": tls: failed to verify certificate: x509: certificate signed by unknown authority
(base) root@toolsvm:/var/www/html/playground/ollama#  ollama pull llava:7b
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/17/170370233dd5c5415250a2ecd5c71586352850729062ccef1496385647293868/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240615%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240615T114123Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=2714941a56fd1fd1fe617dcff5223ca9bdd6cdd91ddc9516312ed92cb872cff7": tls: failed to verify certificate: x509: certificate signed by unknown authority
(base) root@toolsvm:/var/www/html/playground/ollama#

**Comment by tagwato** [comment]
> Hi everyone, this should be fixed now. I'll leave this issue open for a bit longer and provide a longer explanation on what happened here soon (we don't take availability issues like this lightly). Please let me know if you're seeing any more issues!

The problem persists. 
I managed to install ollama version 0.1.47 with a workaround (https://github.com/ollama/ollama/issues/5330).
But, subsequent ollama pull commands fail with "tls: failed to verify certificate: x509: certificate signed by unknown authority".

And the --insecure option has no effect (e.g: ollama pull phi3 --insecure).
