### ISSUE TITLE
serving llama3 does not work

### ISSUE THREAD

**Issue by lambdaofgod** [ollama/ollama#3876]
### What is the issue?

I am able to run llama 3 (`ollama run llama3`) but when I try to run the server I get

>{"error":"model 'llama3' not found, try pulling it first"}

This is in spite of `ollama list` detecting the model.

Specifically I ran

```
curl $LLAMA_URL -d '{
  "model": "llama3",      
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```

### OS

Linux

### Ollama version

0.1.32

**Comment by EverThingy** [comment]
Can you try adding a tag to the model parameter (by default it's `latest`)
```
curl $LLAMA_URL -d '{
  "model": "llama3:latest",      
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```

**Comment by lambdaofgod** [comment]
That's weird, that was the first thing I tried and it didn't work. Must have been fixed by an update.
Thanks!

**Comment by sridvijay** [comment]
I'm still running into the same issue. I've tried `llama3` as well as `llama3:latest` and still get the same error:

`model 'llama3' not found, try pulling it first`.

When I run `ollama list`, I do see the model:

```
ollama list
NAME            ID              SIZE    MODIFIED    
llama3:latest   a6990ed6be41    4.7 GB  5 hours ago
```

I've tried reinstalling `ollama` as well, but no luck either :/

This is running on Ubuntu 20.04

**Comment by lambdaofgod** [comment]
@sridvijay this basically solves it, thanks! I've updated FAQ accordingly in #3936

**Comment by m-aliabbas** [comment]
same error. not solved

**Comment by whichxjy** [comment]
I met the same error. It seems to be related to the model file path.

**Comment by MotivaoCrypto** [comment]
> I'm still running into the same issue. I've tried `llama3` as well as `llama3:latest` and still get the same error:
> 
> `model 'llama3' not found, try pulling it first`.
> 
> When I run `ollama list`, I do see the model:
> 
> ```
> ollama list
> NAME            ID              SIZE    MODIFIED    
> llama3:latest   a6990ed6be41    4.7 GB  5 hours ago
> ```
> 
> I've tried reinstalling `ollama` as well, but no luck either :/
> 
> This is running on Ubuntu 20.04 running ollama 0.1.32
> 
> EDIT:
> 
> I solved it by running `curl -X POST http://localhost:[port]/api/pull -d '{"model":"llama3"}'`.
> 
> Not sure what I got wrong here, as I thought doing `ollama pull llama3` in the command line would result in the same thing, but I guess the models are stored separately if you want to serve? Not sure, but it works!

I don't understand why but this seems to work, thank you

**Comment by wycoal** [comment]
I restart my computer ， then works
