### ISSUE TITLE
llama runner process has terminated: exit status127

### ISSUE THREAD

**Issue by sosojust1984** [ollama/ollama#6541]
### What is the issue?

llama runner process has terminated: exit status127  ?

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3*

**Comment by thelastblt** [comment]
Ditto- running into this issue on Ollama in docker container on ARM Oracle Ubuntu on Oracle Cloud VPS. 

Can post logs, but they're basically the same as pintofbeer's

**Comment by benpatt-bp** [comment]
Same here, Ollama in docker container on Raspberry Pi 5.

**Comment by PaulaScholz** [comment]
Just got this after installing Ollama with curl on a Raspberry Pi 5.  Version 0.3.8

**Comment by barnaclebarnes** [comment]
Got the same on `latest` on Apple Silicon. Rolling back to `0.3.6` works for me.

**Comment by devskale** [comment]
on Oracle Cloud Instance with Ampere CPU

OLLAMA_DEBUG=1 ./ollama run gemma2:2b
Error: llama runner process has terminated: exit status 127

architecture:
Linux ampere aarch64
Operating System: Ubuntu 24.04 LTS
Kernel: Linux 6.8.0-1011-oracle

**Comment by jpfox** [comment]
I use Archlinux `ollama-cuda` package and it seems that `libcudart.so` lib is no more embedded in this package ??
I've installed `cuda` package and it works now.

**Comment by unclemusclez** [comment]
one of these updates also killed my raspberry pi 3b+ how dare

**Comment by sjohn2** [comment]
Thank you, @barnaclebarnes . Downgrading to 0.3.6 fixed it for me on my Pi 5.

**Comment by unclemusclez** [comment]
> Thank you, @barnaclebarnes . Downgrading to 0.3.6 fixed it for me on my Pi 5.

also worked for me

**Comment by SpudGunMan** [comment]
mee too thanks

**Comment by mt50su** [comment]
same here, running ollama on a Raspberry Pi 5, and the log showed the same as pintofbeer's.
ver.0.3.6 works.

**Comment by PaulaScholz** [comment]
How do you install 3.6?  I have a download from Github but don't know how to install it.  Any instructions?

**Comment by MikeLP** [comment]
https://github.com/ollama/ollama/issues/6568#issuecomment-2322023759

This issue affects ROCm build as well.

**Comment by khuezy** [comment]
> How do you install 3.6? I have a download from Github but don't know how to install it. Any instructions? All the instructions on the web involve downloading the default from Ollama, which is 3.8.

curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.3.6 sh

**Comment by jmorganca** [comment]
Hi folks, so sorry about this. A new update is being prepared that will fix this (0.3.9). It should be available later today

**Comment by jmorganca** [comment]
Hi all, this should be fixed in Ollama 0.3.9: https://github.com/ollama/ollama/releases/tag/v0.3.9

Sorry again!

**Comment by devskale** [comment]
i can confirm that Ollama 0.3.9 is now again working ✅ on
OCI Ampere CPU
Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-1011-oracle aarch64)

thanks for the prompt fix

**Comment by MikeLP** [comment]
@jmorganca I still have the issue with ollama 0.3.9 (0.3.6 works well)
➜  ~ ollama run dbrx:132b-instruct-q8_0 
Error: llama runner process has terminated: signal: segmentation fault (core dumped)

Should I create a new issue?

**Comment by sjohn2** [comment]
0.3.9 works fine on RPI 5.0. Thank you, @jmorganca for the quick fix.

**Comment by dhiltgen** [comment]
@MikeLP your crash is most likely unrelated to the root cause of this issue, so I'd suggest opening a new issue.  Please include server logs so we can see how far along it got before crashing on loading this model.

**Comment by sarrcom** [comment]
Same here, running 0.3.14, I noticed this in the server logs:

time=2024-10-22T20:24:19.453+02:00 level=WARN source=gpu.go:437 msg="error looking up nvidia GPU memory"
time=2024-10-22T20:24:19.707+02:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.0166048 model=C:\Users\xxxxxxx\.ollama\models\blobs\sha256-dde5aa3fc5ffc17176b5e8...
time=2024-10-22T20:24:19.707+02:00 level=WARN source=gpu.go:437 msg="error looking up nvidia GPU memory"
time=2024-10-22T20:24:19.945+02:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.2552733 model=C:\Users\xxxxxxx\.ollama\models\blobs\sha256-dde5aa3fc5ffc17176b5e8...
time=2024-10-22T20:24:19.946+02:00 level=WARN source=gpu.go:437 msg="error looking up nvidia GPU memory"
time=2024-10-22T20:24:20.200+02:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.5102787 model=C:\Users\xxxxxxx\.ollama\models\blobs\sha256-dde5aa3fc5ffc17176b5e8...
[GIN] 2024/10/22 - 20:27:02 | 200 |            0s |       127.0.0.1 | GET      "/api/version"

Looks like this is related to:
[https://github.com/ollama/ollama/issues/6928](https://github.com/ollama/ollama/issues/6928)

**Comment by buddha314** [comment]
Getting this error now on 0.7.0 with qwen3:0.6b on Nobara linux

**Comment by ErfanFathi** [comment]
This command works for me:
`systemctl restart ollama.service `
