### ISSUE TITLE
Linux ollama 0.4.0 custom compile for AMD ROCm fails missing ggml_rocm in go compile

### ISSUE THREAD

**Issue by ganakee** [ollama/ollama#7565]
### What is the issue?

Report date: 2024-11-07

During a custom compile of ollama 0.4.0 on Linux (POP OS 22.04) for AMD ROCm GPUs (AMD 6650 GPU), the initial compile works. 

However, when trying to execute the go compile, the compile fails after about two minutes citing exit code 1 and saying the error is unable to find ggml_rocm.

The issue first arose with 0.4.0. Prior compiles (0.3.8 etc.) worked fine.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.0

**Comment by dhiltgen** [comment]
Most likely solved by #7499

**Comment by stephensrmmartin** [comment]
@dhiltgen I just tried your PR, and it did not resolve the issue from the OP.

**Comment by ganakee** [comment]
**The compile still fails even with 0.4.1--newly released..**

I just tried (2024-11-10) with the newly released 0.4.1. I was not clear whether this includes @dhiltgen 's updates.

1. I downloaded 0.4.1.
2. I change to the download directory and run (for my AMD machine): `ROCM_PATH=/opt/rocm CLBlast_DIR=/usr/lib/cmake/CLBlast AMDGPU_TARGETS="gfx1030" /usr/local/go/bin/go generate -tags rocm ./...`
3. The compile completes.
4. Within the `ollama` directory (created above), I run (for my AMD machine):` /usr/local/go/bin/go build -tags rocm .`
5. The` go `compile results in an **error**: 
```
# github.com/ollama/ollama
/home/me/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lggml_rocm: No such file or directory
collect2: error: ld returned 1 exit status
```
Thus, the compile still fails.

I am not sure if it helps, but I poked around the initial compile directories (see result from Step 2 above).
 I found:
```
~/ollama0.41/ollama/llama/build/linux-amd64$ ls
ggml-aarch64.rocm.o  ggml-cuda           ggml.rocm.o
ggml-alloc.rocm.o    ggml-cuda.rocm.o    runners
ggml-backend.rocm.o  ggml-quants.rocm.o  sgemm.rocm.o
```

**Comment by dhiltgen** [comment]
@stephensrmmartin can you try again with the latest update to my branch for the PR?

If it still doesn't find `ggml_rocm` can you share the build logs leading up to that failure so I can see what the `go build` command looked like?  Also share where it was located.

**Comment by stephensrmmartin** [comment]
@dhiltgen 

I assume arch packaging will need to change, so that libggml_rocm.so is located in LIBDIR/ollama/runners, right? 
Or is it always relative to the binary? Must it always look in `../lib/ollama/runners` ?

**Comment by kaleocheng** [comment]
I successfully built the changes in nixpkgs with https://github.com/NixOS/nixpkgs/pull/354969. but I noticed that the location of `libggml_rocm.so` has changed from `dist/linux-amd64/lib/` to `llama/build/linux-amd64/`. This change causes the installPhase to fail because the current logic is:

```
  postInstall = lib.optionalString stdenv.hostPlatform.isLinux ''
    # Copy libggml_*.so and runners into the lib directory
    # Reference: https://github.com/ollama/ollama/blob/v0.4.1/llama/make/gpu.make#L90
    mkdir -p $out/lib
    cp -r dist/*/lib/* $out/lib/
  '';
```
could you confirm this change in the directory structure?

**Comment by stephensrmmartin** [comment]
Additionally, it still does not actually *run* once installed. This may be an arch packaging issue, but arch has it installed to

```
/usr/bin/ollama
/usr/lib/ollama/
---- libggml_rocm.so
---- runners/{cpu, cpu_avx,cpu_avx2,rocm}/ollama_llama_server
```
It throws an error about `libggml_rocm.so` not being found in the /tmp directory it creates.

**Comment by rainbyte** [comment]
I just installed the last updates:

- rocblas 6.2.2-2
- ollama-rocm 0.4.2-1

And run ollama with this command:

```
ollama serve
```

Then I got this error as before:

```txt
/tmp/ollama3240664242/runners/rocm/ollama_llama_server: error while loading shared libraries: libggml_rocm.so: cannot open shared object file: No such file or directory
time=2024-11-16T03:30:42.832-03:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: exit status 127"
```

To make it work I had to do this:

```sh
cp /usr/lib/ollama/libggml_rocm.so /tmp/ollama1482905245/runners/rocm/
```

Or this:

```sh
LD_LIBRARY_PATH=/usr/lib/ollama/ ollama serve
```

I'm using RX 7900 XTX gpu

**Comment by ganakee** [comment]
Report Date: 2024-11-17

**The error still occurs.**

I downloaded the 0.4.2 version from 2024-11-14.

I first run: `ROCM_PATH=/opt/rocm CLBlast_DIR=/usr/lib/cmake/CLBlast AMDGPU_TARGETS="gfx1030" /usr/local/go/bin/go generate -tags rocm ./...`

I then run where the error occurs:
```
~/ollama-0.4.2/ollama$ /usr/local/go/bin/go build -tags rocm .
go: downloading golang.org/x/text v0.20.0
go: downloading golang.org/x/image v0.22.0
# github.com/ollama/ollama
/home/me/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lggml_rocm: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by dhiltgen** [comment]
I updated the [PR](https://github.com/ollama/ollama/pull/7499) over the weekend to try to improve its ability to find the libraries and get the paths set properly.  If folks are still seeing problems at build or runtime with the latest commits on the PR, please let me know by commenting on the PR.

**Comment by ganakee** [comment]
2024-11-26

I just ran as above the newest 0.4.5. The ggml_rocm error still occurs.

```
/usr/local/go/bin/go build -tags rocm .
# github.com/ollama/ollama
/home/me/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lggml_rocm: No such file or directory
collect2: error: ld returned 1 exit status
```

_I tried the PR but cannot get anything to download. I get an error saying the directory is not a repo._

**Comment by ganakee** [comment]
Thanks  @dhiltgen.
### Quick Answer
I was able to build using the PR from about 2024-11-27. 
I was also able to run ollama --version afterwards.
I ran some test queries models.

###Using the PR
I struggled with using the PR code. For others who may be unfamiliar with gh command line and PRs:

1. from a command line, run `gh auth login` (assuming `gh `is installed with `sudo apt install gh`)
2. this will prompt for authentication. I selected the WEB authentication and followed the command line instructions including copying the token and logging into github via the web browser)
3. I created a target directory called `ollama-pr `and switched to this directory.
4. I could not get the code to clone or download. I was NOT able to use the `CODE <>` shortcut of `gh pr checkout 7499` on the[ PR page](https://github.com/ollama/ollama/pull/7499) . 
5. **Instead I used` gh repo clone dhiltgen/ollama`.**  I found this link by looking at the[ PR page](https://github.com/ollama/ollama/pull/7499) and clicking through the  [`dhiltgen:make_targets` link](https://github.com/dhiltgen/ollama/tree/make_targets) right under the page title and then the `CODE <> `shortcut.
6. Now the code is downloaded, I need to build.
7. For me, AMD 6650 GPU, I switched to the ollama subfolder.
8. I make an edit to the `version/version.go` file to show this is a PR version. OPTIONAL but helpful.
9. I switch up to the `ollama `directory and run ROCM_PATH=/opt/rocm CLBlast_DIR=/usr/lib/cmake/CLBlast AMDGPU_TARGETS="gfx1030" /usr/local/go/bin/go generate -tags rocm ./...
10. After several minutes, I ran `/usr/local/go/bin/go build -tags rocm .` (note the closing period)
11. After a few minutes (this is where the build fomrerly ddfailed before @dhiltgen 's updates) and within the `ollama `directory, I verify with `./ollama --version`.

**Comment by ganakee** [comment]
I tried 0.5.0 and the default build fails with the gguf error.

**Comment by dhiltgen** [comment]
The new cmake based build should cover this now.
