### ISSUE TITLE
error on push due to uppercase model name

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama#927]
It may be obvious to us but unless you know it's not obvious that a model needs to be named namespace/model. Can we make the error a bit more helpful? This is related to the uppercase issue with model names

**Comment by BruceMacD** [comment]
Resolved by #1131

**Comment by technovangelist** [comment]
so , the 401 no longer happens, but pushing with uppercase still fails. Can we give a better error or rename during the push?

```
matt@mattconvert:~$ ollama push mattw/HuggingFaceH4_zephyr-7b-beta
retrieving manifest
Error: file does not exist
```

**Comment by jmorganca** [comment]
Will merge this with #336
