### ISSUE TITLE
Nomic Embed text v2

### ISSUE THREAD

**Issue by NickCis** [ollama/ollama#9340]
As far as I understand the `nomic-embed-text` listed in ollama website is the v1 (v1.5). Nomic has released some weeks ago, the nomic embed text v2 model. According to [their blog](https://www.nomic.ai/blog/posts/nomic-embed-text-v2) there are plans to be released it in Ollama (they feture a "coming Soon" flair). Is there any roadmap regarding that or eta?.

Thanks in advanced!

**Comment by tianlichunhong** [comment]
I am waiting for nomic-embed-text-v2-moe in ollama.com. Thank you!

**Comment by RubenMercadePrieto** [comment]
same here. thanks

**Comment by AndriyMulyar** [comment]
Nomic would like to include it as well!

**Comment by NickCis** [comment]
> Nomic would like to include it as well!

Is there anything that we can do in order to contribute it?. I've tried implementing it using [ollama's guide](https://github.com/ollama/ollama/blob/main/docs/import.md) but it throws an unsupported architecture error.

**Comment by marcelMaier** [comment]
It's sad to see that it takes so long we really need nomic as first model in my opinion with good multilingual support.

**Comment by Terramoto** [comment]
It needs to be supported by llama.cpp before it can be added to Ollama
https://github.com/ggml-org/llama.cpp/pull/12466

**Comment by AndriyMulyar** [comment]
Nomic has implemented support into llama.cpp so Ollama now can implement support for it if they choose!

**Comment by AndriyMulyar** [comment]
The eagle has landed in master: https://github.com/ggml-org/llama.cpp/commit/5f5e39e1ba5dbea814e41f2a15e035d749a520bc

Enjoy searching over 100+ languages!
```python
import requests
def dot(va, vb):
    return sum(a*b for a, b in zip(va, vb))
def embed(texts):
    resp = requests.post('http://localhost:8080/v1/embeddings', json=dict(input=texts)).json()
    return [d['embedding'] for d in resp['data']]

docs = ['嵌入很酷', '骆驼很酷']  # 'embeddings are cool', 'llamas are cool'
docs_embed = embed(['search_document: '+d for d in docs])

query = '跟我讲讲嵌入'  # 'tell me about embeddings'
query_embed = embed(['search_query: '+query])[0]
print(f'query: {query!r}')
for d, e in zip(docs, docs_embed):
    print(f'similarity {dot(query_embed, e):.2f}: {d!r}')
```

Output:
```python
query: '跟我讲讲嵌入'
similarity 0.48: '嵌入很酷'
similarity 0.19: '骆驼很酷'
```

You can thank [cebtenzzre](https://github.com/cebtenzzre) at Nomic for doing the hard kernel work!

**Comment by marcelMaier** [comment]
Nice does anyone know if this will automatically be supported with the next ollama version or is there something we can do to support the implementation?

**Comment by rick-github** [comment]
This model will technically be supported in 0.6.8 but the embeddings are not consistent, so seems like it needs more work.
```console
$ curl -s localhost:11434/api/embed -d '{"model":"hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf","input":["嵌入很酷", "骆驼很酷", "why is the sky blue?"]}' | jq -c '.embeddings[]|.[0:3] + ["..."] + .[-3:]'
[-0.02150792,-0.013614742,-0.11065522,"...",0.041796185,-0.07860671,-0.005676387]
[-0.021249399,-0.015446228,-0.094652824,"...",0.017876133,-0.07958552,-0.021361088]
[-0.036460813,0.030190263,-0.11428562,"...",0.011665087,-0.02603364,0.0015948968]
$ curl -s localhost:11434/api/embed -d '{"model":"hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf","input":["嵌入很酷", "骆驼很酷", "why is the sky blue?"]}' | jq -c '.embeddings[]|.[0:3] + ["..."] + .[-3:]'
[-0.024498621,-0.012290989,-0.10965817,"...",0.03894496,-0.0761127,-0.0071863136]
[-0.02111761,-0.012408579,-0.103786476,"...",0.01648188,-0.07950529,-0.007817455]
[-0.029640654,0.033208888,-0.10780826,"...",0.021175131,-0.031900737,-0.002215559]
```

**Comment by rick-github** [comment]
I built llama.cpp from the same commit (https://github.com/ggml-org/llama.cpp/commit/e1e8e099) that ollama is using, and used the GGUF file from the ollama model:
```console
$ for i in {1..5} ; do ./build/bin/llama-embedding  -e -p "嵌入很酷" --verbose-prompt -ngl 99 -m /root/.ollama/models/blobs/sha256-4117e4fa8f2907418026f7ffed5e3f1151dd3a56c34beabb6d51feb433efc4a4 2>/dev/null | grep "^embedding" | cut -c1-150 ; done
embedding 0: -0.029581  0.002231 -0.105505 -0.038347 -0.019517  0.008074  0.017749  0.054689  0.012325 -0.040079 -0.009443 -0.065497 -0.021140 -0.0408
embedding 0: -0.029581  0.002231 -0.105505 -0.038347 -0.019517  0.008074  0.017749  0.054689  0.012325 -0.040079 -0.009443 -0.065497 -0.021140 -0.0408
embedding 0: -0.029581  0.002231 -0.105505 -0.038347 -0.019517  0.008074  0.017749  0.054689  0.012325 -0.040079 -0.009443 -0.065497 -0.021140 -0.0408
embedding 0: -0.029581  0.002231 -0.105505 -0.038347 -0.019517  0.008074  0.017749  0.054689  0.012325 -0.040079 -0.009443 -0.065497 -0.021140 -0.0408
embedding 0: -0.029581  0.002231 -0.105505 -0.038347 -0.019517  0.008074  0.017749  0.054689  0.012325 -0.040079 -0.009443 -0.065497 -0.021140 -0.0408
```
So this looks like an ollama problem, not a llama.cpp or model problem.

**Comment by rick-github** [comment]
This appears fixed as of 0.7.0-rc1
```console
$ for i in {1..5} ; do curl -s localhost:11434/api/embed -d '{"model":"hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf","input":["why is the sky blue?"]}' | jq -c '.embeddings[]|.[0:3] + ["..."] + .[-3:]' ; done
[-0.028988255,0.014166402,-0.11155555,"...",0.0054887156,-0.038328182,0.0059419377]
[-0.028988255,0.014166402,-0.11155555,"...",0.0054887156,-0.038328182,0.0059419377]
[-0.028988255,0.014166402,-0.11155555,"...",0.0054887156,-0.038328182,0.0059419377]
[-0.028988255,0.014166402,-0.11155555,"...",0.0054887156,-0.038328182,0.0059419377]
[-0.028988255,0.014166402,-0.11155555,"...",0.0054887156,-0.038328182,0.0059419377]
```

**Comment by marcelMaier** [comment]
Can confirm it too think we can close this then? @NickCis

**Comment by tianlichunhong** [comment]
Can someone tell me, if I want to use this model with ollama.How can I do. Because I still not find the model in ollama.com. Thanks!

**Comment by rick-github** [comment]
```
ollama pull hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf
```

**Comment by marcelMaier** [comment]
@tianlichunhong U can get it directly from HuggingFace: `ollama pull hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf`

Be aware that the model name after will also be that long and that u have to use the full name.
A workaround would be to create a modelfile to rename it / give it an alias.

**Comment by rick-github** [comment]
> A workaround would be to create a modelfile to rename it / give it an alias.

```
ollama cp hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf nomic-embed-text-v2
```

**Comment by robo3945** [comment]
> > A workaround would be to create a modelfile to rename it / give it an alias.
> 
> ```
> ollama cp hf.co/nomic-ai/nomic-embed-text-v2-moe-gguf nomic-embed-text-v2
> ```

It doesn't work, at least for me :)

I receive this error: "Error: model "https://huggingface.co/nomic-ai/nomic-embed-text-v2-moe-GGUF" not found"

I use Ollama version 0.9.2

**Comment by rick-github** [comment]
You need to pull it before you can create an alias for it.
