### ISSUE TITLE
ollama._types.ResponseError: POST predict: Post "http://127.0.0.1:36555/completion": EOF (status code: -1)

### ISSUE THREAD

**Issue by canapaio** [ollama/ollama#9789]
### What is the issue?

ollama gemma 3 big bug 

ollama._types.ResponseError: POST predict: Post "http://127.0.0.1:36555/completion": EOF (status code: -1)

### Relevant log output

```shell

```

**Comment by jmorganca** [comment]
Hi @canapaio would it be possible to try with 0.6.1, which was released today? https://github.com/ollama/ollama/releases/tag/v0.6.1

This should fix the issue. If not, please let me know and we can re-open this issue.

**Comment by canapaio** [comment]
ollama is broken, sorry bro, gemma3:12b and ollama 0.6.1 is broken

**Comment by CM-IV** [comment]
@jmorganca I am also still getting this issue with ollama 0.6.1 rocm:

![Image](https://github.com/user-attachments/assets/4c7e0d6f-1a9b-4ca7-b01a-4592ade8b61d)

**Comment by TheWhiteWord** [comment]
Same issue here whenever i try to attach an image.  
Here is the report form comfy UI (ollama node), but he issue persists no matter the  app I use for inference:

```bash
025-03-18T20:53:30.442972 - Prompt executed in 3.83 seconds
2025-03-18T20:54:08.259647 - HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
2025-03-18T20:54:22.098317 - got prompt
2025-03-18T20:54:22.364119 - [Ollama Vision]
request query params:

- query: PLease, describe in details the image prvided, giving particular attention to provide details about technical aspect like:
- drawing genre and sub-genere,
- drawing style,
- coloring,
- overall stylistic mood,
with the aim to create a context that will aloow for continuity in generating images from the same visual novel.
- url: http://127.0.0.1:11434
- model: hf.co/bartowski/google_gemma-3-4b-it-GGUF:Q8_0

2025-03-18T20:54:22.364167 -
2025-03-18T20:54:22.474160 - HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 500 Internal Server Error"
2025-03-18T20:54:22.475569 - !!! Exception during processing !!! POST predict: Post "http://127.0.0.1:36365/completion": EOF
```
From what I gathered seems an issue with importing GGUF from other than the official Ollama Q_4. That works fine form me.
Also I found this on reddit, of somebody that said to have fixed it, but haven't been able to reproduce yet:

```
Okay, so now I have finally solved this.

I had to download the raw, safetensor files of Gemma 3, and then quantize them with the ollama --quantize command, with the Modelfile. Now, Gemma 3 Q5_K_M works fine with vision too!
```
